### ISSUE TITLE
No padding on the song/artists name.

### ISSUE THREAD

**Issue by imshrishk** [Vexcited/better-spotify-genres#13]
I know a similar problem was dealt with in #11 but this problem persists in long song/artists names too.

If the song name is large then it covers the other buttons.
This makes the buttons harder to navigate and use. For reference-
![Image](https://github.com/user-attachments/assets/f1c8e676-e77d-4fee-aa86-2cd167fd7ea8)

Also, Spotify does warp the large names unlike what you said [here](https://github.com/Vexcited/better-spotify-genres/issues/11#issuecomment-2543856485) as shown below but when specifically using this extension it goes mayhem. The below is an example when using all the other extensions except this.
![Image](https://github.com/user-attachments/assets/3778061a-552c-4363-b718-c8eb9ec1a852)

Also I am using latest versions of everything so I am expecting no problems to be present there.

**Comment by vexcited** [comment]
That's very interesting! Thanks for mentioning it, will look into it tomorrow when I'll have a bit of free time.

**Comment by imshrishk** [comment]
@Vexcited I know you are pretty busy but did you take a look at this? I have noticed that the names are wrapped before the genres are loaded but as soon as they load, the wrapping disappears and messes up the UI.

**Comment by vexcited** [comment]
Hello, sorry I haven't because of school and deadlines, it'll be fixed one day but I can't say when to be honest... It could next week or in a month. Sorry for the wait, it's a bit hard for me recently.

**Comment by imshrishk** [comment]
No problem, it's not a big deal.

**Comment by vexcited** [comment]
Finally found a proper way to fix this issue.
It preserves marquees and original width/elements from Spotify actual playbar.

![Image](https://github.com/user-attachments/assets/6af08db7-3f58-4d83-8719-f5884342b8b9)

Should be resolved as of [b988a32](https://github.com/Vexcited/better-spotify-genres/commit/b988a32f96e5fa14bf1f2a46c6fed0779b5e83ae), please update your extension and it should all be good now!

**Comment by imshrishk** [comment]
I am not sure why it is happening but it is not working for me.
I have tried the following steps-
1. Remove the extension
2. Reload
3. Install extension again
4. Reload
5. Used 
```
spictify refresh
```
and got
```
spicetify v2.40.5
info Spicetify up-to-date
success Custom CSS is updated
```
6. Closed and started Spotify again and still getting the below

![Image](https://github.com/user-attachments/assets/29875d82-dd88-4396-8620-b1ad233015f7)

Is there anything else that I should have done?

**Comment by vexcited** [comment]
Maybe the cache is not expired yet (because of the Marketplace behavior), so you'd have to probably wait a bit before it gets updated.
In the meantime, you can install locally the extension by following the steps in the README.

**Comment by imshrishk** [comment]
I don't mind waiting, but it is showing last updated on May 1 on Marketplace, and that's why I assumed that there might be some other issue other than cache. Thanks for the help!

**Comment by vexcited** [comment]
Well there's one thing you can do to know: open the devtools and check if you have any log of better-spotify-genres.

I did an update on the logging and an "Initialized" message is logged when Spotify starts.

**Comment by imshrishk** [comment]
I do have an instance in scripts

![Image](https://github.com/user-attachments/assets/408d82df-1308-4f3b-8522-60dee7766181)
But there is no message on console

![Image](https://github.com/user-attachments/assets/7e22ebec-2be6-48b4-944a-8a8ab9caa733)

I am assuming it's due to the
```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
```
But I am able to see genres on my spotify currently

![Image](https://github.com/user-attachments/assets/b42eb622-43d0-4bf9-bf05-a9703bfd9888)

**Comment by vexcited** [comment]
There's no message in the console, the version is outdated, so yeah you'll have to wait until the cache hits...
